const sampleOrders = [
    // Tensile Structure Job
    {
        // Job Details
        "Job_No": "20241122_4050",
  "Client_Name": "Star Dimensions India Pvt. Ltd",
  "Billing_Company": "Star Dimensions India Pvt. Ltd",
  "Billing_Street": "Add: 303, Mathuria Apartment, Near Vishal Hall, Sir M V Road, Andheri (East)",
  "Billing_City": "",
  "Billing_State": "Maharashtra",
  "Billing_Pincode": "400069",
  "Billing_Country": "India",
  "Order_ID": 6840,
  "Order_Date": "22-Nov-2024",
  "Requested_Delivery_Date": "26-Nov-2024",
  "Job_Type": "Tensile",
  "Product_Name": "Top Cover",
  "Client_Instructions": "Its Tarpaulin - 2 Nos\nFabric - B7631 7071\nVariant - Eco",
  "Job_Priority": "Urgent",
  "Job_Stage": "Delivery Stage",
  "Global_Status": "Job Recd by Client",
  "Delivery_Status": "Job Recd by Client",
  "Delivery_Task_Status": "Job Delivered",
  "Prodn_Status": "Production Completed",
  "Job_Sheet_Status": "Job Sheet Completed",
  "Costing_Status": "KP Approved",
  "Costing_Task_Status": "Costing Completed",
  "Design_Status": "KP Approved",
  "Design_Task_Status": "Completed",
  "Packing_Task_Status": "Not Started",
  "Payment_Status": "Payment Pending",
  "Adv_Pmt_Status": "Advance Payment Pending",
  "Crm_Primary_Alias": "Akshay Bhat",
  "Crm_Primary_Email": "akshay.b@luckytech.in",
  "Sales_Owner_Alias": "Swapnil Virkar",
  "Design_Owner_Email": "farhan@luckyinternational.net",
  "Industry": "Tensile / Fabrication",
  "Job_QR_Code": "https://api.qrserver.com/v1/create-qr-code/?data=20241122_4050&size=100x100",
  "Job_Created_Date_Time": "22-Nov-2024 17:32:33",
  "Design_Start_Time_Latest": "23-Nov-2024 09:54:17",
  "Design_End_Time_Latest": "23-Nov-2024 12:47:48",
  "Job_Task_Start_TIme": "23-Nov-2024 17:39:47",
  "Job_Task_End_TIme": "23-Nov-2024 17:41:17",
  "Job_Completion_Time": "24-Nov-2024 00:00:00",
  "Recd_By_Client_Date": "24-Nov-2024",
  "Total_Fabric_Cons_SQM": 41.92,
  "Total_Fabric_Cons_Sq_Ft": 452.00,
  "Running_Meter_Weld": 28,
  "Job_Priority_Flag": "High",
  "Avg_Time_to_Complete_Design_Job": "02:53:31",
  "Order_Date_Ageing": "1 week",
  "Client_Alias": "Star Dimensions India Pvt. Ltd",
  "Client_Email": "",
  "Billing_GSTIN": "",
  "PAN": "",
  "Job_Sheet_Task_Status": "Completed",
  "Job_Sheet_Checker_Approved": true,
  "KP_Released": "23-Nov-2024",
  "Costing_Completed_Time": "23-Nov-2024 13:09:40",
  "Costing_Approved_Time": "25-Nov-2024 13:03:06",
  "Modified_Time": "06-Jan-2025 12:12:24",
  "Added_User": "orders_luckyinternational",
  "Modified_User": "farhan_luckyinternational",
  "Country_of_Delivery": "India",


        // Product Details
        Product_Details: {
          "Job_No": "20241122_4050",
  "Project_Details": "Tarpaulin",
  "Product_Name": "Tarpaulin Top Cover",
  "Structure": "Losberger",
  "UOM": "Set",
  "Total_No_of_Sets": 2,
  "Nos_Per_Set": 2,
  "Qty_Required_Nos": 1,
  "Color": "Grey",
  "Color_Code": "7071",
  "Fabric_Color": "Grey",
  "Fabric_Type": "Tarpaulin Fabric",
  "Fabric_Category": "Tensile Fabric",
  "Fabric_Name": "B7631",
  "GSM": "650",
  "Width_ft": "12",
  "Length_ft": "20",
  "Width_m": "3.66",
  "Length_m": "6.09",
  "Shape": "Rectangle",
  "Surface": "Matt Finish",
  "Membrane_Type": "PVC Coated Fabric",
  "Preferred_Variant": "Eco",
  "Variant_Description": "Standard Tarpaulin Cover with Eyelets",
  "Structure_Type": "Losberger Type Tensile",
  "Installation_Scope": "Includes onsite installation with accessories",
  "Accessories_Included": "Eyelets, Webbing, Rope",
  "Branding_Liner": "No",
  "Printing": "None",
  "Printing_Percent": "0%",
  "Fabric_Lacquering": "Yes",
  "Transparent_Fabric": "No",
  "Weight": "Approx. 12 kg",
  "Package": "Rolled and packed in box",
  "Box_Packing": "Yes",
  "Extra_Margin": "0.15 m",
  "Westage": "2%",
  "Remarks": "Standard tensile tarpaulin cover, grey color, suitable for outdoor use",
  "Installation_Guide": "Provided with installation instructions",
  "Added_User": "orders_luckyinternational",
  "Added_Time": "22-Nov-2024 17:32:31",
  "Modified_User": "farhan_luckyinternational",
  "Modified_Time": "16-Jul-2025 10:20:09",
  "Record_Status": "UNLOCKED",
  "Industry": "Tensile / Tarpaulin",
  "RM_Type": "PVC Fabric Roll",
  "RM_Name": "B7631 7071",
  "Select_Product": "Tarpaulin Cover",
  "Job_Type": "Tensile",
  "Installation": "Included",
  "Installation_Guide_Available": true,
  "Tent_Width_m": "3.66",
  "Tent_Length_m": "6.09",
  "Tent_Required_nos": "2 Nos",
  "Sidewall_Height_m": "2.5",
  "Ht_m": "2.5",
  "Extra_L_Ht": "0.1",
  "Outer_Ht_m": "2.6",
  "Base_Dia_m": "N/A",
  "Top_Dia_m": "N/A",
  "Tank_Ht_m": "N/A",
  "Tank_Dia_m": "N/A",
  "Capcity_Ltrs": "N/A",
  "Type_of_digester": "N/A",
  "Roll_Door_Type": "N/A",
  "Width_flexitank": "N/A",
  "Height_flexitank": "N/A",
  "Length_Flexitank": "N/A",
  "Extra_L_Dia": "N/A",
  "Accessories_Liner": "N/A",
  "Accessories_Biogas": "N/A",
  "Accessories_MultiLookup": "N/A",
  "GSM_STR": "650 GSM",
  "Nos_Var": "N/A",
  "Printing_Task_ID": "N/A",
  "Cutting_Task_ID": "N/A",
  "Job_No_Link": "Linked to Job 20241122_4050",
  "Preferred_Variant_Description": "Economical PVC Tarpaulin fabric option",
  "RM": "PVC Fabric Material",
  "New_RM_Type": "Standard Roll Material",
  "L_m": "6.09",
  "W_m": "3.66",
  "L_Ht_m": "2.5",
  "L_Dia_m": "N/A",
  "L_W_m": "N/A",
  "Ht_m1": "2.5",
  "Extra_L_Ht_m": "0.1",
  "Dia": "N/A",
  "Shape_Type": "Rectangle",
  "Fabric_Type_Description": "PVC Coated Polyester Fabric used for Tarpaulin Applications"

        },

        // Consumption Details
        Consumption_Details: {
            
  "Fabric_Type": "PVC Coated Fabric",
  "Professional_Kador_mtr": "N/A",
  "Design_By": "Lucky",
  "PVC_Rope_Diameter": "N/A",
  "Record_Status": "UNLOCKED",
  "Fabric_Code": "N/A",
  "Plan_Area": 3568.00,
  "Kador_Fabric": "N/A",
  "Color": "Grey",
  "Job_No": "20241122_4050",
  "Color_Code": "N/A",
  "Quantity": 2,
  "Added_User": "zoho_rahul895",
  "Record_ID": "3910758000021748022",
  "No_of_Sets": "N/A",
  "Width_m": 3.20,
  "Roll_Door_Type": "N/A",
  "Added_Time": "23-Nov-2024 12:47:46",
  "Modified_User": "zoho_rahul895",
  "Modified_Time": "23-Nov-2024 12:47:46",
  "Stock_Assignment_ID": "N/A",
  "Total_Qty_SQFT": 452.00,
  "Total_Qty_SQM": "N/A",
  "Project_Details": "Tarpaulin",
  "Weld_Meter": 28.00,
  "Qty_SQM": 41.92,
  "Printing_Area": "N/A",
  "Design_Consumption_Date": "23-Nov-2024 10:55:24",
  "Branding_Logo_QTY": "N/A",
  "Color_1": "N/A",
  "Length_m": 13.10,
  "Requirement": "N/A",
  "Printing_Task_ID": "N/A",
  "Job_Description": "Tensile Structure",
  "UOM": "SQM",
  "Cutting_Task_ID": "N/A",
  "Extra_Percentage": 0.99,
  "PVC_Rope_Consumption": "N/A",
  "Job_Link_No": "20241122_4050"

        }
    },

    // Roll Door Job
    {
       
  "Job_No": "20250219_5218",
  "Job_Type": "Roll Door",
  "Client_Name": "MOTOROLLS",
  "Client_Email": "info@motorolls.co.in",
  "Client_CRM_ID": "4258313000003151012",
  "Client_Alias": "MOTOROLLS",
  "Sales_Owner": ["Swapnil Virkar"],
  "Sales_Owner_Email": "akshay.b@luckytech.in",
  "Design_By": "Lucky",
  "Design_Status": "KP Approved",
  "Design_Start_Date": "20-Feb-2025",
  "Design_Start_Time_Latest": "20-Feb-2025 13:58:29",
  "Design_End_Time_Latest": "20-Feb-2025 15:15:43",
  "KP_Released": "20-Feb-2025",
  "KP_Released_Time": "20-Feb-2025 15:15:43",
  "Checker_Assigned_Time": "20-Feb-2025 15:15:42",
  "Maker_Assigned_Time": "20-Feb-2025 15:15:42",
  "Job_Assigned_Date_Time": "N/A",
  "Job_Created_Date_Time": "19-Feb-2025 10:31:32",
  "Job_Created_Time": "N/A",
  "Job_Sheet_Status": "Job Sheet Completed",
  "Job_Sheet_Task_Status": "Completed",
  "Job_Sheet_Checker_and_Maker": [
    3910758000025496592,
    3910758000025496596,
    3910758000025496600,
    3910758000025496604,
    3910758000025496608
  ],
  "Job_QR_Code": "<img src='https://api.qrserver.com/v1/create-qr-code/?data=20250219_5218&size=100x100' border='0'>",
  "Job_Priority": "Normal",
  "Order_Date": "19-Feb-2025",
  "Order_Date_Ageing": "1 week",
  "Billing_Company": "MOTOROLLS",
  "Billing_Street": "Rajgad soc, G block, Flat no H7, G floor, Chinchwad, Haveli,",
  "Billing_City": "",
  "Billing_State": "Maharashtra",
  "Billing_Pincode": "411019",
  "Billing_Country": "India",
  "Delivery_Street": "",
  "Delivery_City": "",
  "Delivery_State": "",
  "Delivery_Pincode": "N/A",
  "Delivery_Country": "",
  "Requested_Delivery_Date": "23-Feb-2025",
  "Delivery_Status": "Not Requested",
  "Transport_Mode": "N/A",
  "Client_Instructions": "Please refer attachments for measurements.\n\nWith Logo Printing",
  "Job_Stage": "Costing Stage",
  "Job_Task_Start_Time": "28-Feb-2025 10:08:55",
  "Job_Task_End_Time": "28-Feb-2025 12:14:27",
  "Current_Updating_Task": "N/A",
  "Global_Status": "KP Approved",
  "Design_Delay_Reasons": "N/A",
  "Avg_Time_to_Complete_Design_Job": "01:17:14",
  "Costing_Status": "Checker Approved",
  "Costing_Task_Status": "Costing Completed",
  "Costing_Start_Time": "20-Feb-2025 16:58:21",
  "Costing_Completed_Time": "21-Feb-2025 13:58:06",
  "Costing_Uploaded_Time": "21-Feb-2025 13:58:06",
  "Costing_Approved": "N/A",
  "Adv_Pmt_Status": "Advance Payment Pending",
  "Payment_Status": "Payment Pending",
  "Design_Owner": [3910758000014657003],
  "Production_Owner_Name": "N/A",
  "Production_Owner_Status": "N/A",
  "Packing_Task_Status": "Not Started",
  "Packing_Owner_Assigned_Time": "N/A",
  "Cutting_Task_Status": "Primary Checklist Not Completed",
  "Cutting_Start_Time": "N/A",
  "Cutting_End_Time": "21-Feb-2025 13:38:28",
  "Cutting_Resource_Allocation_Status": "N/A",
  "Printing_Status": "N/A",
  "Printing_Owner": "N/A",
  "Printing_Owner_Status": "N/A",
  "Printing_Task_Status": "N/A",
  "Folding_Status": "N/A",
  "Welding_Status": "N/A",
  "Welding_Owner_Name": "N/A",
  "Welding_Owner_Status": "N/A",
  "Outstanding_Balance_Summary": "N/A",
 

        Product_Details: {
          
  "UOM": "Nos",
  "Fabric_Type": "N/A",
  "Revise_KP_Id": "N/A",
  "Type_of_Digester": "N/A",
  "Stock_Assignment_Id": "N/A",
  "Width_m": "N/A",
  "Branding_Liner": "N/A",
  "Tank_Height_m": "N/A",
  "Capacity_Ltrs": "N/A",
  "Industry": "Tensile Structures",
  "New_RM_Type": "N/A",
  "Color_Code": "7071",
  "Liner_Type": "N/A",
  "Remarks": "N/A",
  "Tent_Required_Nos": "N/A",
  "Base_Dia_m": "N/A",
  "Width_Flexitank": "N/A",
  "Fabric_Category": "Translucent",
  "Record_ID": "3910758000025146026",
  "Select_Cone_Type": "N/A",
  "Top_Dia_m": "N/A",
  "L_L_m": "N/A",
  "Roll_Door_Type": "N/A",
  "L_Ht_m": "N/A",
  "Fabric_Color_Code": "7071",
  "Installation_Guide": "N/A",
  "Total_No_of_Sets": "N/A",
  "Project_Details": "N/A",
  "Color": "Grey",
  "Product_Name": "Tarpaulin",
  "Select_Product": "N/A",
  "Width_ft": "N/A",
  "Tent_Width_m": "N/A",
  "RM_Name": "N/A",
  "Height_Flexitank": "N/A",
  "Weight": "N/A",
  "Job_No_Link": "20250219_4063",
  "Accessories_MultiLookup": "N/A",
  "Job_Type": "N/A",
  "Installation_Scope": "N/A",
  "Length_Flexitank": "N/A",
  "Ht_m": "N/A",
  "New_RM": "N/A",
  "L_m": "N/A",
  "Package": "N/A",
  "RM": "High-Strength Coated Fabric",
  "Remarks1": "N/A",
  "Remarks2": "N/A",
  "Extra_L_Ht": "N/A",
  "Fabric": "N/A",
  "Preferred_Variant": "N/A",
  "Shape": "N/A",
  "Job_No": "N/A",
  "L_W_m": "N/A",
  "Record_Status": "UNLOCKED",
  "Outer_Ht_m": "N/A",
  "Length_ft": "N/A",
  "Surface": "N/A",
  "Accessories_Liner": "N/A",
  "Variant_Description": "N/A",
  "GSM_STR": "N/A",
  "Inner_Ht_m": "N/A",
  "Tent_Length_m": "N/A",
  "Membrane_Type": "N/A",
  "Extra_L_Dia": "N/A",
  "Fabric_Lacquering": "N/A",
  "Printing_Percent": "N/A",
  "RM_Type": "PVC-Coated Textile",
  "Added_User": "orders_luckyinternational",
  "Tank_Dia_m": "N/A",
  "Structure": "Losberger",
  "Dia": "N/A",
  "Webbing": "N/A",
  "Added_Time": "19-Feb-2025 10:31:31",
  "GSM": "650 GSM",
  "Modified_User": "accounts4703",
  "Printing": "No",
  "Nos_Per_Set": "N/A",
  "Accessories_Biogas": "Yes",
  "Length_ft1": "N/A",
  "Modified_Time": "21-Feb-2025 13:58:05",
  "Installation": "N/A",
  "Transparent_Fabric": "0.8 mm",
  "Sidewall_Height": "N/A",
  "Nos_Var": "N/A",
  "Printing_Task_ID": "N/A",
  "Cutting_Task_ID": "N/A",
  "Westage": "N/A",
  "L_Dia_m": "N/A",
  "Extra_Margin": "N/A",
  "Fabric_Name": "N/A",
  "Qty_Required_Nos": 4,
  "Box_Packing": "N/A",
  "Ht_m1": "N/A",
  "Fabric_Color": "Grey"

        },

        // Consumption Details
        Consumption_Details: {
  "Fabric_Type": "PVC-Coated Fabric",
  "Professional_Kador_mtr": "N/A",
  "Design_By": "Lucky",
  "PVC_Rope_Diameter": "5 mm",
  "Record_Status": "UNLOCKED",
  "Fabric_Code": "F1234",
  "Plan_Area": "N/A",
  "Kador_Fabric": "N/A",
  "Color": "Grey",
  "Job_No": "20250220_4080",
  "Color_Code": "7071",
  "Quantity": 4,
  "Added_User": "zoho_rahul895",
  "Record_ID": "3910758000025202031",
  "No_of_Sets": "N/A",
  "Width_m": 3.00,
  "Roll_Door_Type": "Modular",
  "Added_Time": "20-Feb-2025 15:15:42",
  "Modified_User": "zoho_rahul895",
  "Modified_Time": "20-Feb-2025 15:15:42",
  "Stock_Assignment_ID": "N/A",
  "Total_Qty_SQFT": "N/A",
  "Total_Qty_SQM": "N/A",
  "Project_Details": "N/A",
  "Weld_Meter": 135.00,
  "Qty_SQM": 31.20,
  "Printing_Area": "N/A",
  "Design_Consumption_Date": "20-Feb-2025 15:02:52",
  "Branding_Logo_QTY": "N/A",
  "Color_1": "Grey",
  "Length_m": 10.40,
  "Requirement": "Standard Modular Tensile",
  "Printing_Task_ID": "N/A",
  "Job_Description": "Tensile Structure",
  "UOM": "Nos",
  "Cutting_Task_ID": "N/A",
  "Qty_SQFT": 336.00,
  "Extra": "N/A",
  "PVC_Rope_Consumption_m": 79.00,
  "Job_Link_No": "20250220_4080"

        }
    }
];

const industryFields = {
    'Tensile': {
        productFields: [
  "Product_Name",
  "Project_Details",
  "Fabric_Category",
  "Fabric_Type",
  "Fabric_Name",
  "Qty_Required_Nos",
  "UOM",
  "Nos_Per_Set",
  "Total_No_of_Sets",
  "Fabric_Color",
  "Color_Code",
  "GSM_STR",
  "Width_m",
  "Length_m",
  "Remarks",
  "Preferred_Variant",
  "Variant_Description",
  
  "Added_User",
  "Added_Time"
]

    },
    'Roll Door': {
        productFields: [
  "Product_Name",
  "Project_Details",
  "Fabric_Category",
  "Fabric_Type",
  "Fabric_Name",
  "Qty_Required_Nos",
  "UOM",
  "Nos_Per_Set",
  "Total_No_of_Sets",
  "Fabric_Color",
  "Color_Code",
  "GSM_STR",
  "Width_m",
  "Length_m",
  "Remarks",
  "Preferred_Variant",
  "Variant_Description",
  "Roll_Door_Type",
  "Structure",
  "Transparent_Fabric",
  "Printing",
  "Added_User",
  "Added_Time"
]

    }
};
